localTranslations(){
  return [
    {
      "en":"QR Master: Scanner & Creator",
      "pt":"QR Master: Scanner e Criador",
      "es":"QR Master: Escáner y Creador",
      "de":"QR Master: Scanner & Ersteller",
      "fr":"QR Master : Scanner et Créateur",
      "it":"QR Master: Scanner e Creatore",
    },
    {
      "en":"home",
      "pt":"início",
      "es":"inicio",
      "de":"startseite",
      "fr":"accueil",
      "it":"inizio",
    },
    {
      "en":"history",
      "pt":"Histórico",
      "es":"Historial",
      "de":"Verlauf",
      "fr":"historique",
      "it":"storico",
    },
    {
      "en":"create",
      "pt":"criar",
      "es":"crear",
      "de":"Erstellen",
      "fr":"créer",
      "it":"crea",
    },
    {
      "en":"suscriptions",
      "pt":"Assinaturas",
      "es":"Suscripciones",
      "de":"Abonnements",
      "fr":"abonnements",
      "it":"abbonamenti",
    },
    {
      "en":"scan QR",
      "pt":"Escanear QR",
      "es":"escanear QR",
      "de":"QR-Code scannen",
      "fr":"scanner un code QR",
      "it":"scansiona codice QR",
    },
    {
      "en":"faster: Generate and save your QR codes without limits with Pro.",
      "pt":"Mais rápido: Gere e guarde os seus códigos QR sem limites com o Pro.",
      "es":"Más rápido: Genera y guarda tus códigos QR sin límites con Pro.",
      "de":"schneller: Erstelle und speichere deine QR-Codes ohne Limits mit Pro.",
      "fr":"plus rapide : générez et enregistrez vos codes QR sans limite avec Pro.",
      "it":"più veloce: genera e salva i tuoi codici QR senza limiti con Pro.",
    },
    {
      "en":"code detected",
      "pt":"Código detectado",
      "es":"Código detectado",
      "de":"Code erkannt",
      "fr":"code détecté",
      "it":"codice rilevato",
    },
    {
      "en":"continue scanning",
      "pt":"Continuar a escanear",
      "es":"Continuar escaneando",
      "de":"Weiter scannen",
      "fr":"continuer à scanner",
      "it":"continua a scansionare",
    },
    {
      "en":"QR code value copied successfully",
      "pt":"Valor do código QR copiado com sucesso",
      "es":"Valor del código QR copiado correctamente",
      "de":"QR-Code-Wert erfolgreich kopiert",
      "fr":"valeur du code QR copiée avec succès",
      "it":"valore del codice QR copiato con successo",
    },
    {
      "en":"return to the beginning",
      "pt":"Voltar ao início",
      "es":"volver al inicio",
      "de":"Zurück zum Anfang",
      "fr":"retour au début",
      "it":"torna all'inizio",
    },
    {
      "en":"text",
      "pt":"texto",
      "es":"texto",
      "de":"Text",
      "fr":"texte",
      "it":"testo",
    },
    {
      "en":"text without special characters",
      "pt":"texto sem caracteres especiais",
      "es":"texto sin caracteres especiales",
      "de":"Text ohne Sonderzeichen",
      "fr":"texte sans caractères spéciaux",
      "it":"testo senza caratteri speciali",
    },
    {
      "en":"12 digits + 1 checksum digit",
      "pt":"12 dígitos + 1 dígito de verificação",
      "es":"12 dígitos + 1 dígito de suma de comprobación",
      "de":"12 Ziffern + 1 Prüfziffer",
      "fr":"12 chiffres + 1 chiffre de contrôle",
      "it":"12 cifre + 1 cifra di controllo",
    },
    {
      "en":"type",
      "pt":"tipo",
      "es":"tipo",
      "de":"Typ",
      "fr":"type",
      "it":"tipo",
    },
    {
      "en":"save",
      "pt":"salvar",
      "es":"guardar",
      "de":"speichern",
      "fr":"sauvegarder",
      "it":"salva",
    },
    {
      "en":"search",
      "pt":"pesquisar",
      "es":"buscar",
      "de":"suchen",
      "fr":"rechercher",
      "it":"cerca",
    },
    {
      "en":"scanner result",
      "pt":"resultado do scanner",
      "es":"resultado del escáner",
      "de":"Scanner-Ergebnis",
      "fr":"résultat du scanner",
      "it":"risultato della scansione",
    },
    {
      "en":"saved successfully",
      "pt":"salvo com sucesso",
      "es":"guardado correctamente",
      "de":"erfolgreich gespeichert",
      "fr":"sauvegardé avec succès",
      "it":"salvato con successo",
    },
    {
      "en":"web",
      "pt":"site",
      "es":"sitio web",
      "de":"Webseite",
      "fr":"site web",
      "it":"sito web",
    },

    {
      "en":"name",
      "pt":"nome",
      "es":"nombre",
      "de":"Name",
      "fr":"nom",
      "it":"nome",
    },
    {
      "en":"company",
      "pt":"empresa",
      "es":"empresa",
      "de":"Firma",
      "fr":"entreprise",
      "it":"azienda",
    },
    {
      "en":"email address",
      "pt":"endereço de e-mail",
      "es":"dirección de correo electrónico",
      "de":"E-Mail-Adresse",
      "fr":"adresse e-mail",
      "it":"indirizzo email",
    },
    {
      "en":"address",
      "pt":"endereço",
      "es":"dirección",
      "de":"Adresse",
      "fr":"adresse",
      "it":"indirizzo",
    },
    {
      "en":"phone",
      "pt":"telefone",
      "es":"Teléfono",
      "de":"Telefon",
      "fr":"téléphone",
      "it":"telefono",
    },
    {
      "en":"fax",
      "pt":"fax",
      "es":"fax",
      "de":"Fax",
      "fr":"fax",
      "it":"fax",
    },
    {
      "en":"landline",
      "pt":"telefone fixo",
      "es":"Teléfono fijo",
      "de":"Festnetz",
      "fr":"téléphone fixe",
      "it":"telefono fisso",
    },
    {
      "en":"copy",
      "pt":"copiar",
      "es":"copiar",
      "de":"kopieren",
      "fr":"copier",
      "it":"copia",
    },
    {
      "en":"URL not found",
      "pt":"URL não encontrado",
      "es":"url no encontrada",
      "de":"URL nicht gefunden",
      "fr":"URL non trouvée",
      "it":"URL non trovato",
    },
    {
      "en":"add contact",
      "pt":"adicionar contacto",
      "es":"agregar contacto",
      "de":"Kontakt hinzufügen",
      "fr":"ajouter un contact",
      "it":"aggiungi contatto",
    },
        {
      "en":"contact",
      "pt":"contacto",
      "es":"contacto",
      "de":"Kontakt",
      "fr":"contact",
      "it":"contatto",
    },
    {
      "en":"show map",
      "pt":"mostrar mapa",
      "es":"mostrar mapa",
      "de":"Karte anzeigen",
      "fr":"afficher la carte",
      "it":"mostra mappa",
    },
    {
      "en":"problems saving contact",
      "pt":"problemas ao salvar contacto",
      "es":"problemas para guardar el contacto",
      "de":"Probleme beim Speichern des Kontakts",
      "fr":"problèmes lors de l'enregistrement du contact",
      "it":"problemi durante il salvataggio del contatto",
    },
    {
      "en":"permission denied",
      "pt":"permissão negada",
      "es":"permiso denegado",
      "de":"Berechtigung verweigert",
      "fr":"permission refusée",
      "it":"permesso negato",
    },
    {
      "en":"body",
      "pt":"corpo",
      "es":"cuerpo",
      "de":"Textkörper",
      "fr":"corps",
      "it":"corpo",
    },
    {
      "en":"subject",
      "pt":"assunto",
      "es":"asunto",
      "de":"Betreff",
      "fr":"sujet",
      "it":"oggetto",
    },
    {
      "en":"send mail to",
      "pt":"enviar e-mail para",
      "es":"enviar correo a",
      "de":"E-Mail senden an",
      "fr":"envoyer un e-mail à",
      "it":"invia email a",
    },
    {
      "en":"send",
      "pt":"enviar",
      "es":"enviar",
      "de":"senden",
      "fr":"envoyer",
      "it":"invia",
    },
    {
      "en":"created",
      "pt":"criados",
      "es":"creados",
      "de":"erstellt",
      "fr":"créés",
      "it":"creati",
    },
    {
      "en":"scanned",
      "pt":"escaneados",
      "es":"escaneados",
      "de":"gescannt",
      "fr":"scannés",
      "it":"scansionati",
    },
{
      "en":"create QR",
      "pt":"Criar QR",
      "es":"Crear QR",
      "de":"QR erstellen",
      "fr":"Créer QR",
      "it":"Crea QR",
    },
    {
      "en":"no scans yet. Point your camera at a QR code to get started!",
      "pt":"Ainda não há digitalizações. Aponte a sua câmara para um código QR para começar!",
      "es":"Aún no hay escaneos. ¡Apunte su cámara a un código QR para comenzar!",
      "de":"Noch keine Scans. Richten Sie Ihre Kamera auf einen QR-Code, um zu beginnen!",
      "fr":"Aucun scan pour le moment. Pointez votre appareil photo vers un code QR pour commencer !",
      "it":"Nessuna scansione ancora. Punta la fotocamera su un codice QR per iniziare!",
    },
    {
      "en":"you don’t have any QR codes yet. Tap below to create your first one!",
      "pt":"Ainda não tens códigos QR. Clica abaixo para criar o teu primeiro!",
      "es":"Aún no tienes códigos QR. ¡Toca abajo para crear tu primero!",
      "de":"Sie haben noch keine QR-Codes. Tippen Sie unten, um Ihren ersten zu erstellen!",
      "fr":"Vous n'avez pas encore de codes QR. Appuyez ci-dessous pour créer votre premier !",
      "it":"Non hai ancora codici QR. Tocca qui sotto per crearne il tuo primo!",
    },
    {
      "en":"wifi",
      "pt":"wifi",
      "es":"wifi",
      "de":"WLAN",
      "fr":"wifi",
      "it":"wifi",
    },
    {
      "en":"password",
      "pt":"senha",
      "es":"contraseña",
      "de":"Passwort",
      "fr":"mot de passe",
      "it":"password",
    },
    {
      "en":"auth type",
      "pt":"tipo de autenticação",
      "es":"tipo de autenticación",
      "de":"Authentifizierungstyp",
      "fr":"type d'authentification",
      "it":"tipo di autenticazione",
    },
    {
      "en":"connect",
      "pt":"conectar",
      "es":"conectar",
      "de":"verbinden",
      "fr":"connecter",
      "it":"connetti",
    },
    {
      "en":"location",
      "pt":"localização",
      "es":"ubicación",
      "de":"Standort",
      "fr":"localisation",
      "it":"posizione",
    },
    {
      "en":"view location",
      "pt":"ver localização",
      "es":"ver ubicación",
      "de":"Standort anzeigen",
      "fr":"afficher la localisation",
      "it":"vedi posizione",
    },
    {
      "en":"description",
      "pt":"descrição",
      "es":"descripción",
      "de":"Beschreibung",
      "fr":"description",
      "it":"descrizione",
    },
    {
      "en":"event venue",
      "pt":"local do evento",
      "es":"lugar del evento",
      "de":"Veranstaltungsort",
      "fr":"lieu de l'événement",
      "it":"luogo dell'evento",
    },
    {
      "en":"final date",
      "pt":"data final",
      "es":"fecha final",
      "de":"Enddatum",
      "fr":"date de fin",
      "it":"data finale",
    },
    {
      "en":"initial date",
      "pt":"data inicial",
      "es":"fecha inicial",
      "de":"Startdatum",
      "fr":"date de début",
      "it":"data iniziale",
    },
    {
      "en":"title",
      "pt":"título",
      "es":"título",
      "de":"Titel",
      "fr":"titre",
      "it":"titolo",
    },
    {
      "en":"phone number",
      "pt":"número de telefone",
      "es":"número de teléfono",
      "de":"Telefonnummer",
      "fr":"numéro de téléphone",
      "it":"numero di telefono",
    },
    {
      "en":"message",
      "pt":"mensagem",
      "es":"mensaje",
      "de":"Nachricht",
      "fr":"message",
      "it":"messaggio",
    },
    {
      "en":"code type",
      "pt":"tipo de código",
      "es":"tipo de código",
      "de":"Code-Typ",
      "fr":"type de code",
      "it":"tipo di codice",
    },
    {
      "en":"select format",
      "pt":"selecionar formato",
      "es":"seleccionar formato",
      "de":"Format wählen",
      "fr":"sélectionner le format",
      "it":"seleziona formato",
    },
    {
      "en":"invalid phone number",
      "pt":"número de telefone inválido",
      "es":"número de teléfono inválido",
      "de":"Ungültige Telefonnummer",
      "fr":"numéro de téléphone invalide",
      "it":"numero di telefono non valido",
    },
    {
      "en":"phone number",
      "pt":"número de telefone",
      "es":"número de teléfono",
      "de":"Telefonnummer",
      "fr":"numéro de téléphone",
      "it":"numero di telefono",
    },

    {
      "en":"search and select country",
      "pt":"pesquisar e selecionar país",
      "es":"buscar y seleccionar país",
      "de":"Land suchen und auswählen",
      "fr":"rechercher et sélectionner un pays",
      "it":"cerca e seleziona paese",
    },
    {
      "en":"flashlight",
      "pt":"lanterna",
      "es":"linterna",
      "de":"Taschenlampe",
      "fr":"torche",
      "it":"torcia",
    },

    {
      "en":"please enter a valid value",
      "pt":"por favor, insira um valor válido",
      "es":"por favor, ingrese un valor válido",
      "de":"Bitte geben Sie einen gültigen Wert ein",
      "fr":"veuillez saisir une valeur valide",
      "it":"si prega di inserire un valore valido",
    },
    {
      "en":"advanced settings",
      "pt":"configurações avançadas",
      "es":"configuración avanzada",
      "de":"Erweiterte Einstellungen",
      "fr":"paramètres avancés",
      "it":"impostazioni avanzate",

    },
    {
      "en":"cirlce",
      "pt":"círculo",
      "es":"círculo",
      "de":"Kreis",
      "fr":"cercle",
      "it":"cerchio",
    },
    {
      "en":"QR dot shape",
      "pt":"formato dos pontos do QR",
      "es":"forma de los puntos del QR",
      "de":"QR-Punktform",
      "fr":"forme des points QR",
      "it":"forma dei punti QR",
    },
    {
      "en":"change color QR dot shape",
      "pt":"mudar cor do formato dos pontos QR",
      "es":"cambiar color de la forma de los puntos QR",
      "de":"Farbe der QR-Punktform ändern",
      "fr":"changer la couleur de la forme des points QR",
      "it":"cambia colore della forma dei punti QR",
    },

    {
      "en":"select color",
      "pt":"selecionar cor",
      "es":"selecciona un color",
      "de":"Farbe auswählen",
      "fr":"sélectionner une couleur",
      "it":"seleziona un colore",
    },
    {
      "en":"cancel",
      "pt":"cancelar",
      "es":"cancelar",
      "de":"Abbrechen",
      "fr":"annuler",
      "it":"annulla",
    },
    {
      "en":"change color data module shape",
      "pt":"mudar cor do formato do módulo de dados",
      "es":"cambiar color de la forma del módulo de datos",
      "de":"Farbe der Datenmodulform ändern",
      "fr":"changer la couleur de la forme du module de données",
      "it":"cambia colore della forma del modulo dati",
    },
    {
      "en":"change background color",
      "pt":"mudar cor de fundo",
      "es":"cambiar color de fondo",
      "de":"Hintergrundfarbe ändern",
      "fr":"changer la couleur d'arrière-plan",
      "it":"cambia colore di sfondo",
    },

    {
      "en":"change logo",
      "pt":"mudar logótipo",
      "es":"cambiar logotipo",
      "de":"Logo ändern",
      "fr":"changer le logo",
      "it":"cambia logo",
    },
    {
      "en":"square",
      "pt":"quadrado",
      "es":"cuadrado",
      "de":"Quadrat",
      "fr":"carré",
      "it":"quadrato",
    },
    {
      "en":"first name",
      "pt":"nome",
      "es":"nombre",
      "de":"Vorname",
      "fr":"prénom",
      "it":"nome",
    },
    {
      "en":"last name",
      "pt":"sobrenome",
      "es":"apellido",
      "de":"Nachname",
      "fr":"nom",
      "it":"cognome",
    },
    {
      "en":"post",
      "pt":"cargo",
      "es":"cargo",
      "de":"Position",
      "fr":"poste",
      "it":"incarico",
    },
    {
      "en":"company name",
      "pt":"nome da empresa",
      "es":"nombre de la empresa",
      "de":"Firmenname",
      "fr":"nom de l'entreprise",
      "it":"nome dell'azienda",
    },
    {
      "en":"network name",
      "pt":"nome da rede",
      "es":"nombre de la red",
      "de":"Netzwerkname",
      "fr":"nom du réseau",
      "it":"nome della rete",
    },
    {
      "en":"type",
      "pt":"tipo",
      "es":"tipo",
      "de":"Typ",
      "fr":"type",
      "it":"tipo",
    },
    {
      "en":"the WPA/WPA2/WPA3 encryption method requires a password with at least 8 characters.",
      "pt":"o método de criptografia WPA/WPA2/WPA3 requer uma senha com pelo menos 8 caracteres.",
      "es":"el metodo de cifrado WPA/WPA2/WPA3 requiere una contraseña con al menos 8 caracteres",
      "de":"Die WPA/WPA2/WPA3-Verschlüsselungsmethode erfordert ein Passwort mit mindestens 8 Zeichen.",
      "fr":"la méthode de chiffrement WPA/WPA2/WPA3 nécessite un mot de passe d'au moins 8 caractères.",
      "it":"il metodo di crittografia WPA/WPA2/WPA3 richiede una password con almeno 8 caratteri.",
    },
    {
      "en": "remove qr",
      "pt": "remover qr",
      "es": "eliminar qr", 
      "de": "QR entfernen",
      "fr": "supprimer qr",
      "it": "rimuovi qr",
    },
    {
      "en": "if you're sure you want to delete it, you won't be able to get it back.",
      "pt": "se tem certeza que deseja eliminá-lo, não poderá recuperá-lo",
      "es": "si está seguro de eliminarlo, no podrá recuperarlo posteriormente",
      "de": "wenn Sie sicher sind, dass Sie es löschen möchten, werden Sie es nicht wiederherstellen können",
      "fr": "si vous êtes sûr de vouloir le supprimer, vous ne pourrez pas le récupérer",
      "it": "se sei sicuro di volerlo eliminare, non potrai recuperarlo",
    },
    {
      "en": "yes, Remove",
      "pt": "sim, Remover",
      "es": "sí, Eliminar",
      "de": "ja, Entfernen",
      "fr": "oui, Supprimer",
      "it": "sì, Rimuovi",
    },
    {
      "en": "done!",
      "pt": "concluído!",
      "es": "¡realizado!",
      "de": "erledigt!",
      "fr": "terminé!",
      "it": "fatto!",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },


    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
      {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },


    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
      {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },


    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
      {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },


    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
      {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },


    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
      {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },


    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
      {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },


    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
      {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },


    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },

    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },
    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },


    {
      "en":"",
      "pt":"",
      "es":"",
      "de":"",
      "fr":"",
      "it":"",
    },




    
  ];

}